# Site settings
title: Michael A. Brewington
email: mike@brewingtonmedia.com
description: > # this means to ignore newlines until "baseurl:"
  A simple quick reference.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brewingtonmedia.com" # the base hostname & protocol for your site
twitter_username: brewingtonmedia
github_username:  mikebrew
#exclude: [theocratic]

# Build settings
markdown: kramdown
