baseURL = 'http://mikebrew.github.io/'
languageCode = 'en-us'
title = 'mikebrew.github.io'
theme = 'ananke'
sectionPagesMenu = 'main'
canonifyURLs = true
relativeURLs = true

pygmentsStyle = "monokailight"

[params]
ordersectionsby = "weight" # ordersectionsby = "title"
disableSearch = false # default is false
disableReadmoreNav = true # set true to hide prev/next navigation, default is false
highlightClientSide = true # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = true # set true to open shortcuts links to a new tab/window
